#browser selection
browser =chrome
#application url
url =https://magento.softwaretestingboard.com/
#application credentials
login_username =seleniumsquad2024@gmail.com
login_password =SeleniumSquad@123
qty=3
firstname =kavitha
lastname =rajesh
address=82, jyothy nagar, adyar
